name: Secret Scan

on:
  push:
    branches:
      - main
      - fix
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    name: Scan for secrets
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy Secret Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          exit-code: 1
          severity: HIGH,CRITICAL
